---
title: "RCML network theory"
author: "Indiogine and Kulm"
date: "27 October 2014"
output: word_document
---

Initial settings, libraries and cleanup.
```{r initial, message=FALSE, warning=FALSE}
options(width=120)
rm(list=ls())
library(xlsx)
library(psych)
library(pmr)
setwd("~/Code/RCML/")
```
<!---- do not use headers, page numbes, footers and footnotes ---->
<!---- 1/4 inch paragraph indentation  ---->
<!---- 1 inch margins ---->
<!----  max pages = 8 including references ---->
<!---- Font Times 12-pt, 1.5 line spacing, no extra lines between paragraphs ---->
<!---- Theoretical framework and related literature, methodology, findings ---->
<!---- center title on first page, all caps. Below authors, affiliation, email ---->

# USING NETWORK THEORY TO ANALYZE ALGEBRA PROBLEM SOLVING STRATEGIES

# Abstract
<!---- less than 100 words ---->
The purpose of our study was to assess a specific subject of the content knowledge (CK) of middle school mathematicspreserviceteachers, namely problem solving. We used two related mathematical concepts, network theory and edit distance, to analyze algebra problem solving strategies. This methodology has not yet been applied to analyze how students solve algebra word problems. Each word problem solution was atomized into distinct steps and a linear graph was created where each node represented a step and successive steps were connected by directed edges. Then all the graphs were merged into a singleacyclicaldirected weighted graph. We were able to determine the most frequent type of solution strategy and the distance between each solution path and those that we considered to be optimal. A larger distance was considered a sign of lower CK as well as the use of guess-and-check solutions. We present the results of this analysis andrelate dthem topreserviceCK as evinced from test scores and teacher self-efficacy.

# Theoretical Framework

The research presented here is part of a larger study aimed at investigating and enhancing the pedagogical content knowledge and mathematics content knowledge of middle school preservice teachers (PSTs), as well as their cultural and equity awareness (see e.g. Brown et al., 2011; Merchant et al., 2013; Indiogine et al., 2014).

In this presentation we focus on the algebra problem solving strategies (steps) used by the preservice teachers. Problem solving is an important component of their content knowledge (CK). Their problem solving skills are also relevant to their pedagogical content knowledge (PCK). For instance, a PST who primarily employes guess-and-check strategies to solve an algebra word problemmost likely doesso due to lack of CK and will thus be not able to properly teach algebra problem solving.

Algebra problem solving, i.e. wordproblems, is a difficult subject to master and also to teach (Kulm, 1982, Kieran, 1992). Many attempts have been made to facilitate the mastering of problem solving in algebra even though George Polya's How to Solve It is still popular more than 60 years after its original publication (Polya, 1945). Little research has been done on how students, including PSTs, solve word problems. Examples of this type of research are Reed et al. (2012), Akkus Cakiroglu (2006), and Van Dooren et al. (2003).

Here we propose the use of network theory (Idous Wilson, 2000) to provide us with an efficient and promising way to study how algebra word problems are solved. Network theory provides the means to study graphsmathematically. A graph can be defined as a set of objects (nodes) that are connected by links (edges).Ricca Green (in press) used network theory to analyze the progress made by college calculus students during the course. Woolcott et al. (2014) employed network analysis to examine the connections between learned concepts and concepts inherent in assessment items (p. 385). However, network theory has not yet been used to analyze algebra problem solving itself. In addition, we use the related concept of edit distance (Cormode Muthukrishnan, 2007) to measure the difference between paths through a graph.

Several features of network analysis make it very useful in the analysis of problem solving, (1) the graphic representations of the network offer us and immediate and intuitive representation of the problem solving strategies, (2) the quantification the problem solving strategies obtained by calculating (2.1) the edit distances from strategies deemed optimal, (2.2) the path lengths, and (2.3) path weights give us and aggregate value of these strategies. In addition, by knowing which strategies were used and how frequently we are able to determine the CK and PCK gaps of the PSTs and can can thus adjust the math methods course. We can perform a network analysis during the successive semesters and thus gauge the efficacy of the course adjustments.

# Methodology

# Findings

# References
